services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level info
    volumes:
      - ./dir-api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env-dev
      - .env
    depends_on:
      - db
  db:
    image: postgis/postgis:17-3.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env-dev
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: